main: de.spookly.SpooklyCorePlugin
name: SpooklyCore
version: '${version}'
api-version: 1.21
website: https://spookly.net
authors:
  - Niklas Ehlen
depend:
  - SpooklyCloudnetUtils
libraries:
  - 'org.mongodb:mongodb-driver-reactivestreams:${mongodb_driver_version}'
  - 'org.mongodb:mongodb-crypt:${mongodb_crypt_version}'