main: de.spookly.SpooklyCorePlugin
name: SpooklyCore
version: '${version}'
api-version: 1.21
website: https://spookly.net
authors:
  - Niklas Ehlen
depend:
  - SpooklyCloudnetUtils
libraries:
  - org.mongodb:mongodb-driver-reactivestreams:5.1.0
  - org.mongodb:mongodb-crypt:1.8.0